name: Second Github Action

on:
  push:
    branches:
      - main
    

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Second Github Action"
        shell: zsh

